info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Bookshelf API
  version: "1.0"
paths:
  /v1/book/create:
    post:
      consumes:
      - application/json
      description: Add new book
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: add new book
      tags:
      - Books
  /v1/book/view:
    get:
      description: Get book by id
      parameters:
      - description: book id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: get book by id
      tags:
      - Books
  /v1/healthz:
    get:
      consumes:
      - application/json
      description: Check current service's health
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: health check
      tags:
      - Miscellaneous
  /v1/user/view:
    get:
      description: Get user by id
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: get user by id
      tags:
      - Users
  /v1/version:
    get:
      description: Check current service's version
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: version check
      tags:
      - Miscellaneous
swagger: "2.0"
